### ISSUE TITLE
Enable FreeRTOS building

### ISSUE THREAD

**Issue by asl** [access-softek/msp430-clang#49]
https://www.freertos.org/

**Comment by dmikushin** [comment]
Started, will publish our patches on top of here: https://github.com/dmikushin/msp430-clang-freertos

**Comment by dmikushin** [comment]
Existing FreeRTOS MSP430X demos are for CCS and IAR. Issues currently on my table:
* We need to do our own build system w/o CCS and IAR, finding and attaching all dependencies
* We need to create ports tree with some utility functions that have CCS/IAR-specific syntax
* We need to cope with `__bic_SR_register_on_exit` and friends

**Comment by dmikushin** [comment]
Current work-in-progress commit: 0166ca0c23829ef1d8cb52df849fa4cf210d7036

**Comment by dmikushin** [comment]
In this commit we now offer Clang-based MSP430X demos build: https://github.com/dmikushin/msp430-clang-freertos/commit/2850684a213eee821dbb7371e2143afa2bbeb937

Currently, clang is used only for compiling C sources. Asm compilation and linking is done by gcc.

The `full_demo` image occupies almost entire FRAM. In order to fit FRAM, we have to shrink stack down to e.g. `__idle_stack_size__=0x100` and place it into RAM.

```
   text	   data	    bss	    dec	    hex	filename
   8152	    176	  14822	  23150	   5a6e	blinky_demo
msp430-elf-size full_demo
   text	   data	    bss	    dec	    hex	filename
  29590	   1606	  16634	  47830	   bad6	full_demo
```

Please feel free to reopen if anything else is to be done here.
